-- 코드를 작성해주세요


# SELECT *
# FROM FISH_INFO
# ORDER BY LENGTH DESC 
# LIMIT 10

SELECT F.ID,F.LENGTH
FROM FISH_INFO AS F
JOIN(
SELECT ID
FROM FISH_INFO
ORDER BY LENGTH DESC
LIMIT 10) AS FI ON F.ID=FI.ID
ORDER BY F.LENGTH DESC