-- 코드를 작성해주세요

SELECT II.ITEM_ID,ITEM_NAME,RARITY
FROM ITEM_INFO AS II
JOIN ITEM_TREE AS IT
ON II.ITEM_ID=IT.ITEM_ID
WHERE II.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL )
ORDER BY II.ITEM_ID DESC


# SELECT *
# FROM ITEM_TREE 
# WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE)

