-- 코드를 입력하세요

# 틀린 내 풀이 

# SELECT F.FLAVOR
# FROM FIRST_HALF AS F
# JOIN JULY AS H
# ON F.SHIPMENT_ID=H.SHIPMENT_ID
# GROUP BY F.FLAVOR
# ORDER BY SUM(F.TOTAL_ORDER+H.TOTAL_ORDER) DESC
# LIMIT 3


SELECT FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
    UNION ALL
    SELECT FLAVOR, SUM(TOTAL_ORDER)
    FROM JULY
    GROUP BY FLAVOR
) AS ALL_ORDERS
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC
LIMIT 3;
