-- 코드를 입력하세요

# 1차 에러 코드
# SELECT WRITER_ID,SUM(PRICE)
# FROM USED_GOODS_BOARD 
# GROUP BY WRITER_ID
# HAVING STATUS='DONE'
# HAVING 절은 GROUP BY 이후에 그룹화된 결과를 필터링할 때 사용됩니다.

SELECT USER_ID,NICKNAME,SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD  AS UB
JOIN USED_GOODS_USER AS UU
ON UB.WRITER_ID=UU.USER_ID
WHERE STATUS='DONE'
GROUP BY UU.USER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES
