-- 코드를 작성해주세요

SELECT B.ITEM_ID, (SELECT ITEM_NAME FROM ITEM_INFO WHERE ITEM_ID=B.ITEM_ID) AS ITEM_NAME, (SELECT RARITY FROM ITEM_INFO WHERE ITEM_ID=B.ITEM_ID) AS RARITY
FROM ITEM_INFO AS A
LEFT JOIN ITEM_TREE AS B
ON A.ITEM_ID=B.PARENT_ITEM_ID
WHERE RARITY='RARE' AND B.ITEM_ID IS NOT NULL
ORDER BY B.ITEM_ID DESC