-- 코드를 입력하세요

# 총 주문량이 3,000QHEK
# SELECT FLAVOR
# FROM FIRST_HALF
# GROUP BY FLAVOR
# HAVING SUM(TOTAL_ORDER)>3000


# SELECT FLAVOR
# FROM ICECREAM_INFO
# WHERE INGREDIENT_TYPE='sugar_based'


SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN ICECREAM_INFO B ON A.FLAVOR=B.FLAVOR
WHERE (A.TOTAL_ORDER > 3000) AND (B.INGREDIENT_TYPE="fruit_based")
ORDER BY A.TOTAL_ORDER DESC
