-- 코드를 작성해주세요

# 첫 오답

# SELECT ID, FISH_NAME, LENGTH
# FROM FISH_INFO AS FI
# JOIN FISH_NAME_INFO FNI
# ON FI.FISH_TYPE=FNI.FISH_TYPE
# WHERE LENGTH IN
#     (
#         SELECT MAX(LENGTH)
#         FROM FISH_INFO AS FI
#         JOIN FISH_NAME_INFO FNI
#         ON FI.FISH_TYPE=FNI.FISH_TYPE
#         GROUP BY FI.FISH_TYPE
#     )
# ORDER BY ID ASC



SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO AS FI
JOIN FISH_NAME_INFO AS FN
ON FI.FISH_TYPE=FN.FISH_TYPE
WHERE FI.ID IN
    (
        SELECT ID
        FROM FISH_INFO
        WHERE (FISH_TYPE, LENGTH) IN
            (
                SELECT FISH_TYPE,MAX(LENGTH)
                FROM FISH_INFO 
                GROUP BY FISH_TYPE
        )
    )
ORDER BY FI.ID


